pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/madanNeeraj/simple-java-maven-app'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
